### ISSUE TITLE
replacement: bao # into /

### ISSUE THREAD

**Issue by chung88** [BioAssayOntology/BAO#23] opened 2018-11-14 16:28 UTC
bao#, which make it difficult or impossible to resolve the IRI (server does not seem to get the info after the #).
change all URIs and make one or more files of all deprecated terms with the forward link.

**Comment by sschurer** [comment] 2018-11-19 19:32
We've discussed this for the last two meetings, i.e. a months or more with individuals from all teams and based on that decided to make that change. It sounds like we need to think this through again. the URLs with # in it are not resolvable and create a maintenance problem. Therefore we wanted to fix this ASAP.

**Comment by sschurer** [comment] 2018-11-19 19:35
Could we run a test of global replace of # in BAO URIs with some datasets?

**Comment by aclarkxyz** [comment] 2018-11-19 20:05
ASAP would've been ca. 2012, it's way too late now.

**Comment by whinis** [comment] 2018-11-19 20:13
@aclarkxyz As far as I can find there is no way to retrieve the part after the # in any server language as per RFCs the part after the # is not considered part of the URL and no client should send it to the server. 
https://tools.ietf.org/html/rfc3986
https://superuser.com/questions/487323/wget-with-url-that-contains
https://stackoverflow.com/questions/3408664/how-to-detect-and-redirect-from-url-with-anchor-using-mod-rewrite-htaccess

If you managed to get it working on your side maybe you can point me to the code that makes it work unless we want to require all clients use javascript and then have a client side script do a redirect

**Comment by whinis** [comment] 2018-11-19 21:56
Its not a matter of fixing it on the website, I can make a javascript that sort of does what we need but the problem is it only works in a browser and only if they have javascript enabled because no client is suppose to send the fragment and any that do are liable to change at any moment since the RFC says your not suppose to.

**Comment by aclarkxyz** [comment] 2018-11-19 22:31
I was under the impression that the "#" part of the URL was included in the original HTTP request, in the same way as the query "?" part is. If the browser is stripping out the hash section and never sending it to the server (I haven't actually tested that use case), then the solution I was proposing obviously won't work. On the other hand if the "#" part is still visible to JavaScript, you could fix it after the fact, and redirect to an analogous information page.

Regardless of whether it requires a hack on the server or a hack on the page, it should be possible to make it largely indistinguishable to users, and that doesn't involve breaking every BAO use case.

**Comment by whinis** [comment] 2018-11-19 23:16
The # part might be in some browsers but its not considered part of the URL and is purely for client side and its called the anchor or the fragment. So it shouldn't be included in any HTTP requests and any server that does receive it is suppose to ignore it even if it is received. The # part is visible to JavaScript and HTML on the page so you can then redirect it but its certainly less than ideal and would only work in browsers.

**Comment by ianwdunlop** [comment] 2018-11-20 09:35
You should think very carefully before changing any BAO URLS. I know of many projects using it and their users will be have a set of existing URLS they use to look for things. Changing them will break many applications. If you want to make this change then deprecate the '#' based URLS and remove it a few releases down the road after publicisng the change far and wide. Would take years for a change of this magnitude to ripple through the user base.

**Comment by sschurer** [comment] 2018-11-20 15:15
Let's figure all options to solve this problem:
Somehow resolve the # URIs? How?
Have a global redirect / deprecation so that the old URIs will stay valid. However this may require the resolving the URIs in the first place. This may be an option if resolving them required a lot of maintenance.
Work with each customer to prep the change.
Others?

**Comment by sschurer** [comment] 2018-11-28 17:38
To add to this. we also confirmed the W3C specs for URIs, which explicitly
specify URIs with the fragment separator #
So these URIs are good to stay.

**Closed** 2018-11-28 19:54 UTC
Labels: Priority-High
